-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.DELIVERY (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  Timestamp timestamp without time zone,
  Bill Date timestamp without time zone,
  Delivery Order No. text,
  Party Name text,
  Product Name text,
  Quantity Delivered. numeric,
  Bill No. text,
  Losgistic no. text,
  Rate Of Material numeric,
  Type Of Transporting text,
  Transporter Name text,
  Vehicle Number. text,
  Bilty Number. text,
  Giving From Where text,
  Indent No. text,
  Qty numeric,
  Planned 1 date,
  Actual 1 date,
  Delay 1 numeric,
  Image Of Slip text,
  Image Of Slip2 text,
  Image Of Slip3 text,
  Remarks text,
  Actual Qty loaded In Truck (Total Qty) numeric,
  Actual Qty As Per Weighment Slip numeric,
  Planned 2 date,
  Actual 2 timestamp without time zone,
  Delay 2 numeric,
  Planned 3 date,
  Actual3 timestamp without time zone,
  Delay3 numeric,
  Bilty Copy text,
  Bilty No. text,
  Planned 4 date,
  Actual4 timestamp without time zone,
  Delay4 numeric,
  D-Sr Number text,
  CONSTRAINT DELIVERY_pkey PRIMARY KEY (id)
);
CREATE TABLE public.DISPATCH (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  Timestamp timestamp without time zone,
  D-Sr Number text,
  Delivery Order No. text,
  Party Name text,
  Product Name text,
  Qty To Be Dispatched numeric,
  Type Of Transporting text,
  Date Of Dispatch timestamp without time zone,
  To Be Reconfirm text,
  Planned1 timestamp without time zone,
  Actual1 timestamp without time zone,
  Delay1 numeric,
  LGST-Sr Number text,
  Actual Truck Qty numeric,
  Type Of Transporting   text,
  Transporter Name text,
  Truck No. text,
  Driver Mobile No. text,
  Vehicle No. Plate Image text,
  Bilty No. text,
  Type Of Rate text,
  Transport Rate @Per Matric Ton numeric,
  Fixed Amount numeric,
  Planned2 timestamp without time zone,
  Actual2 timestamp without time zone,
  Delay2 numeric,
  Loading Image 1 text,
  Loading Image 2 text,
  Loading Image 3 text,
  Planned3 timestamp without time zone,
  Actual3 timestamp without time zone,
  Delay3 numeric,
  Planned4 timestamp without time zone,
  Actual4 timestamp without time zone,
  Delay4 numeric,
  Trust Certificate Made text,
  TC Required text,
  CONSTRAINT DISPATCH_pkey PRIMARY KEY (id)
);
CREATE TABLE public.MASTER (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  Firm Name text,
  Party Name text,
  Address text,
  GST Number text,
  Customer Category text,
  Type of PI text,
  Marketing Sales Person text,
  Product Name text,
  UOM text,
  Transporter Name text,
  Material Return Transporter Name text,
  CONSTRAINT MASTER_pkey PRIMARY KEY (id)
);
CREATE TABLE public.Material Return (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  Time Stamp timestamp without time zone NOT NULL,
  D.O Number character varying NOT NULL,
  Party Name text NOT NULL,
  Product Name text NOT NULL,
  Qty numeric NOT NULL,
  Tranport Payment text,
  Reason Of Material Return text,
  Return No. numeric NOT NULL,
  Bilty No. character varying,
  Planned timestamp without time zone,
  Actual timestamp without time zone,
  Debit Note Copy text,
  Bill Copy text,
  Transporter Name text,
  Vehicle No. character varying,
  Type Of Rate character varying,
  Rate numeric,
  Planned2 timestamp without time zone,
  Actual2 timestamp without time zone,
  Qty Of Return Material numeric,
  Rate Of Material numeric,
  Condition of Material text,
  Photo Of Return Material text,
  Planned3 timestamp without time zone,
  Actual3 timestamp without time zone,
  Credit Note No. character varying,
  Credit Note Copy text,
  Amount numeric,
  Photo Of Email Sent text,
  Planned4 timestamp without time zone,
  Actual4 timestamp without time zone,
  Debit Note text,
  Planned5 timestamp without time zone,
  Actual5 timestamp without time zone,
  CONSTRAINT Material Return_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ORDER RECEIPT (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  Timestamp timestamp without time zone,
  DO-Delivery Order No. text,
  PARTY PO NO (As Per Po Exact) text,
  Party PO Date timestamp without time zone,
  Party Names text,
  Product Name text,
  Quantity numeric,
  Rate Of Material numeric,
  Type Of Transporting text,
  Upload SO text,
  Is This Order Through Some Agent text,
  Order Received From text,
  Type Of Measurement text,
  Contact Person Name text,
  Contact Person WhatsApp No. text,
  Alumina% numeric,
  Iron% numeric,
  Type Of PI text,
  Lead Time For Collection Of Final Payment integer,
  Type Of Application text,
  Customer Category text,
  Free Replacement (FOC) text,
  Gst Number text,
  Address text,
  Firm Name text,
  Total PO Basic Value numeric,
  Payment to Be Taken text,
  Advance numeric,
  Basic numeric,
  Retention Payment text,
  Retention Percentage numeric,
  Lead Time for Retention integer,
  Specific Concern text,
  Reference No. text,
  Adjusted Amount numeric,
  Marketing Mangager Name text,
  Delivered numeric,
  Pending Qty numeric,
  Material Return text,
  Status text,
  Complete Date timestamp without time zone,
  Crm For The Customer text,
  Mail text,
  Planned 1 timestamp without time zone,
  Actual 1 timestamp without time zone,
  Time Delay 1 numeric,
  Expected Delivery Date timestamp without time zone,
  Planned 2 timestamp without time zone,
  Actual 2 timestamp without time zone,
  Time Delay 2 numeric,
  Planned 3 timestamp without time zone,
  Actual 3 timestamp without time zone,
  Time Delay 3 numeric,
  In Stock Or Not text,
  Order Number Of The Production text,
  Qty Transferred numeric,
  Batch Number In Remarks text,
  Planned 4 timestamp without time zone,
  Actual 4 timestamp without time zone,
  Time Delay 4 numeric,
  Type Of Packaging text,
  TC Required text,
  CONSTRAINT ORDER RECEIPT_pkey PRIMARY KEY (id)
);
CREATE TABLE public.POST DELIVERY (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  Timestamp timestamp without time zone,
  Order No. text,
  Type of Bill text,
  Bill No. text,
  Bill Date date,
  Party Name text,
  Total Bill Amount numeric,
  Total Truck Qty numeric,
  Copy Of Bill text,
  Planned timestamp without time zone,
  Actual timestamp without time zone,
  Delay numeric,
  Material Received Date date,
  Image Of Received Bill / Audio text,
  Grn Number text,
  CONSTRAINT POST DELIVERY_pkey PRIMARY KEY (id)
);
CREATE TABLE public.USER (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  Username text NOT NULL,
  Password text NOT NULL,
  Role text,
  Page Acess text,
  Firm_Name text,
  CONSTRAINT USER_pkey PRIMARY KEY (id)
);