-- Table for storing transporter options for a PO
CREATE TABLE public.po_transporters (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  po_id bigint REFERENCES public."ORDER RECEIPT"(id) ON DELETE CASCADE,
  transporter_name text NOT NULL,
  contact_number text,
  rate numeric,
  availability text,
  status text DEFAULT 'Pending', -- 'Pending', 'Approved', 'Rejected'
  remarks text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT po_transporters_pkey PRIMARY KEY (id)
);

-- Extend ORDER RECEIPT for workflow tracking
ALTER TABLE public."ORDER RECEIPT"
ADD COLUMN IF NOT EXISTS logistics_status text DEFAULT 'Pending Arrangement'; -- 'Pending Arrangement', 'Pending Approval', 'Approved'

ALTER TABLE public."ORDER RECEIPT"
ADD COLUMN IF NOT EXISTS approved_transporter_id bigint REFERENCES public.po_transporters(id) ON DELETE SET NULL;

-- Create constraint to limit max 3 transporters per PO
CREATE OR REPLACE FUNCTION check_max_transporters()
RETURNS TRIGGER AS $$
BEGIN
  IF (SELECT count(*) FROM public.po_transporters WHERE po_id = NEW.po_id) >= 3 THEN
    RAISE EXCEPTION 'Maximum 3 transporters allowed per PO';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER enforce_max_transporters
BEFORE INSERT ON public.po_transporters
FOR EACH ROW EXECUTE FUNCTION check_max_transporters();
