create table public."DISPATCH" (
  id bigint generated always as identity not null,
  "Timestamp" timestamp without time zone null,
  "D-Sr Number" text null,
  "Delivery Order No." text null,
  "Party Name" text null,
  "Product Name" text null,
  "Qty To Be Dispatched" numeric null,
  "Type Of Transporting" text null,
  "Date Of Dispatch" timestamp without time zone null,
  "To Be Reconfirm" text null,
  "Planned1" timestamp without time zone null,
  "Actual1" timestamp without time zone null,
  "Delay1" numeric null,
  "LGST-Sr Number" text null,
  "Actual Truck Qty" numeric null,
  "Type Of Transporting  " text null,
  "Transporter Name" text null,
  "Truck No." text null,
  "Driver Mobile No." text null,
  "Vehicle No. Plate Image" text null,
  "Bilty No." text null,
  "Type Of Rate" text null,
  "Transport Rate @Per Matric Ton" numeric null,
  "Fixed Amount" numeric null,
  "Planned2" timestamp without time zone null,
  "Actual2" timestamp without time zone null,
  "Delay2" numeric null,
  "Loading Image 1" text null,
  "Loading Image 2" text null,
  "Loading Image 3" text null,
  "Planned3" timestamp without time zone null,
  "Actual3" timestamp without time zone null,
  "Delay3" numeric null,
  "Planned4" timestamp without time zone null,
  "Actual4" timestamp without time zone null,
  "Delay4" numeric null,
  constraint DISPATCH_pkey primary key (id)
) TABLESPACE pg_default;
