-- Table for storing transporter options for a PO (legacy flow)
CREATE TABLE IF NOT EXISTS public.po_transporters (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  po_id bigint REFERENCES public."ORDER RECEIPT"(id) ON DELETE CASCADE,
  transporter_name text NOT NULL,
  contact_number text,
  rate numeric,
  availability text,
  status text DEFAULT 'Pending',
  remarks text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT po_transporters_pkey PRIMARY KEY (id)
);

-- Extend ORDER RECEIPT for workflow tracking
ALTER TABLE public."ORDER RECEIPT"
ADD COLUMN IF NOT EXISTS logistics_status text DEFAULT 'Pending Arrangement';

ALTER TABLE public."ORDER RECEIPT"
ADD COLUMN IF NOT EXISTS approved_transporter_id bigint REFERENCES public.po_transporters(id) ON DELETE SET NULL;

-- Legacy trigger to limit max 3 transporter options per PO
CREATE OR REPLACE FUNCTION check_max_transporters()
RETURNS TRIGGER AS $$
BEGIN
  IF (SELECT count(*) FROM public.po_transporters WHERE po_id = NEW.po_id) >= 3 THEN
    RAISE EXCEPTION 'Maximum 3 transporters allowed per PO';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS enforce_max_transporters ON public.po_transporters;

CREATE TRIGGER enforce_max_transporters
BEFORE INSERT ON public.po_transporters
FOR EACH ROW EXECUTE FUNCTION check_max_transporters();

-- New parent table for submitted logistics plans
CREATE TABLE IF NOT EXISTS public.po_logistics_plans (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  po_id bigint NOT NULL REFERENCES public."ORDER RECEIPT"(id) ON DELETE CASCADE,
  mode text NOT NULL CHECK (mode IN ('single', 'split')),
  status text NOT NULL DEFAULT 'Pending Approval' CHECK (status IN ('Pending Approval', 'Approved', 'Rejected')),
  created_by text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT po_logistics_plans_pkey PRIMARY KEY (id)
);

-- Child table for individual split allocations
CREATE TABLE IF NOT EXISTS public.po_logistics_splits (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  plan_id bigint NOT NULL REFERENCES public.po_logistics_plans(id) ON DELETE CASCADE,
  po_id bigint NOT NULL REFERENCES public."ORDER RECEIPT"(id) ON DELETE CASCADE,
  transporter_name text NOT NULL,
  contact_number text,
  rate numeric,
  availability text,
  remarks text,
  allocated_qty numeric NOT NULL CHECK (allocated_qty > 0),
  status text DEFAULT 'Pending Approval',
  check_delivery_actual timestamp without time zone,
  check_delivery_in_stock_or_not text,
  production_order_no text,
  qty_transferred numeric,
  batch_number_remarks text,
  indent_self_batch_number text,
  gp_percent numeric,
  dispatch_record_id bigint,
  lgst_sr_number text,
  sort_order integer DEFAULT 0,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT po_logistics_splits_pkey PRIMARY KEY (id)
);

ALTER TABLE public.po_logistics_splits
ADD COLUMN IF NOT EXISTS status text DEFAULT 'Pending Approval';

ALTER TABLE public.po_logistics_splits
ADD COLUMN IF NOT EXISTS check_delivery_actual timestamp without time zone;

ALTER TABLE public.po_logistics_splits
ADD COLUMN IF NOT EXISTS check_delivery_in_stock_or_not text;

ALTER TABLE public.po_logistics_splits
ADD COLUMN IF NOT EXISTS production_order_no text;

ALTER TABLE public.po_logistics_splits
ADD COLUMN IF NOT EXISTS qty_transferred numeric;

ALTER TABLE public.po_logistics_splits
ADD COLUMN IF NOT EXISTS batch_number_remarks text;

ALTER TABLE public.po_logistics_splits
ADD COLUMN IF NOT EXISTS indent_self_batch_number text;

ALTER TABLE public.po_logistics_splits
ADD COLUMN IF NOT EXISTS gp_percent numeric;

ALTER TABLE public.po_logistics_splits
ADD COLUMN IF NOT EXISTS dispatch_record_id bigint;

ALTER TABLE public.po_logistics_splits
ADD COLUMN IF NOT EXISTS lgst_sr_number text;

ALTER TABLE public."ORDER RECEIPT"
ADD COLUMN IF NOT EXISTS approved_logistics_plan_id bigint REFERENCES public.po_logistics_plans(id) ON DELETE SET NULL;

ALTER TABLE public."DISPATCH"
ADD COLUMN IF NOT EXISTS po_id bigint;

ALTER TABLE public."DISPATCH"
ADD COLUMN IF NOT EXISTS logistics_plan_id bigint;

ALTER TABLE public."DISPATCH"
ADD COLUMN IF NOT EXISTS logistics_split_id bigint;
